[build]
command = "npm build"
functions = "lambda"

# this is actually a Rewrite
# totally optional, but makes up for
# a much better UX
[[redirects]]
from = "/*"
to = "/portfolio/:splat"
status = 200
