
#functions = "/opt/build/repo/opt/build/repo/lambda"

[build]
command = "npm run-script build"
commandOrigin = "config"
[environment]
REVIEW_ID = "9"
publish = "/opt/build/repo/dist"
#functions = "/opt/build/repo/lambda"

# this is actually a Rewrite
# totally optional, but makes up for
# a much better UX

[[redirects]]
from = "/*"
status = 200
to = "/portfolio/:splat"

